name: Call reusable workflow
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  sayHelloandGoodbye:
    uses: vramaprasad/reusable-sayhelloandgoodbye/.github/workflows/hello-goodbye.yaml@main
    secrets: inherit
    with:
      name: Engineering Retreat

  sayHelloAgain:
    needs: sayHelloandGoodbye
    uses: vramaprasad/reusable-sayhelloagain/.github/workflows/say-helloagain.yaml@main
    secrets: inherit
    with:
      name: ${{ needs.sayHelloandGoodbye.outputs.name }}
